name: AVR Build and Release
# This GitHub Actions workflow automates the process of building and releasing AVR projects.
# It triggers on push events to the main branch, excluding markdown files to optimize the build process.
# The workflow runs on an Ubuntu latest environment and performs several key actions:
# 1. Checks out the repository to access the project code.
# 2. Builds a Docker image based on the Dockerfile located in the .devcontainer directory.
# 3. Configures and runs build steps inside the Docker container using CMake, compiling the AVR project.
# 4. Archives the compiled binaries and uploads them as artifacts.
# 5. Retrieves the previous release tag and calculates the next version number based on semantic versioning rules.
# 6. Creates a new release on GitHub, making the compiled artifacts available for download.
# 7. Uploads the compiled binaries (.hex & .elf) to the newly created release.
#
# Additionally, it's configured to handle permissions for contents, issues, and pull-requests operations.
# Uncomment the `pull_request` section to enable this workflow for pull requests to the main branch as well.

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
#   pull_request:
#     branches:
#       - main
#     paths-ignore:
#       - '**.md' # Ignore markdown changes in PRs for builds

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # required for github-action-get-previous-tag
      
      # Build the Docker image from Dockerfile in the .devcontainer directory
      - name: Build Docker Image
        run: docker build .devcontainer --file .devcontainer/Dockerfile --tag my-dev-container

      # Run commands inside the Docker container
      - name: Configure CMake
        run: docker run --rm -v $PWD:/project -w /project my-dev-container cmake -S . -B build

      - name: Build
        run: |
          docker run --rm -v $PWD:/project -w /project my-dev-container mkdir -p build
          docker run --rm -v $PWD:/project -w /project my-dev-container cmake --build build

      # Archive the compiled artifacts for upload
      - name: Archive Production Artifacts for Upload
        uses: actions/upload-artifact@v2
        with:
          name: compiled-artifacts
          path: |
            build/*.hex
            build/*.elf

      # Get latest release number
      - name: Get Previous tag
        id: previoustag
        uses: 'WyriHaximus/github-action-get-previous-tag@v1'
        with:
          # Optional fallback tag to use when no tag can be found (First release will be 1.0.0)
          fallback: 0.9.9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Get Next Minor Version
        id: semver
        uses: 'WyriHaximus/github-action-next-semvers@v1'
        with:
          version: ${{ steps.previoustag.outputs.tag }}

      # Compute the next version based on the previous tag
      - name: Compute Next Version
        id: compute_version
        run: |
          PREVIOUS_TAG=${{ steps.previoustag.outputs.tag }}
          IFS='.' read -ra VERSION <<< "$PREVIOUS_TAG"
          MAJOR=${VERSION[0]}
          MINOR=${VERSION[1]}
          PATCH=${VERSION[2]}

          # Increment the version
          if [ "$MINOR" -eq 9 ] && [ "$PATCH" -eq 9 ]; then
              # If both minor and patch are at 9, increment major and reset others
              MAJOR=$((MAJOR+1))
              MINOR=0
              PATCH=0
          elif [ "$PATCH" -eq 9 ]; then
              # If patch is at 9, increment minor and reset patch
              MINOR=$((MINOR+1))
              PATCH=0
          else
              # Default behavior: increment patch
              PATCH=$((PATCH+1))
          fi

          NEXT_VERSION="$MAJOR.$MINOR.$PATCH"
          echo "Next version: $NEXT_VERSION"
          echo "::set-output name=version::$NEXT_VERSION"

      # Create a release and upload the compiled artifacts
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.compute_version.outputs.version }}
          release_name: Release ${{ steps.compute_version.outputs.version }}
          draft: false # Make the release public (true makes it visible only to collaborators)
          prerelease: false # Indicate that this is unstable pre-release

      - name: Upload .HEX File to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/avr-firmware.hex
          asset_name: avr-firmware.hex
          asset_content_type: application/octet-stream

      - name: Upload .ELF File to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/avr-firmware.elf
          asset_name: avr-firmware.elf
          asset_content_type: application/octet-stream